# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Framed < Formula
  desc ""
  homepage "https://github.com/mactat/framed"
  version "0.0.9"

  on_macos do
    url "https://github.com/mactat/framed/releases/download/v0.0.9/framed_0.0.9_darwin_all.tar.gz"
    sha256 "8af833f6eeaaf3d46be1a1e42bb55b5d25d03b979c1b51bf47ea3ead7aad6fcf"

    def install
      bin.install "framed"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/mactat/framed/releases/download/v0.0.9/framed_0.0.9_linux_amd64.tar.gz"
      sha256 "fb673d320ab8f4313806712ec52c760d839c326da4d608746061d4e067aa48b3"

      def install
        bin.install "framed"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mactat/framed/releases/download/v0.0.9/framed_0.0.9_linux_arm64.tar.gz"
      sha256 "bad09f668bbed2ac1ff390e319c745f7d7155bafa69721c09b87123d9ca026e7"

      def install
        bin.install "framed"
      end
    end
  end
end
